### ISSUE TITLE
When I run the training code after download COMA dataset, it pop out below error message, would you please help me? thanks 

### ISSUE THREAD

**Issue by semchan** [zxchen110/Deep3DMM#2]
RuntimeError: The size of tensor a (29990) must match the size of tensor b (5023) at non-singleton dimension 0

**Comment by zchen06** [comment]
Can you upload a screenshot of the output message? I cannot locate the position where the error happens. 
My guess is like this. Are you running the code from scratch? Did you run the CoMA code from Ranjan et al. 2018 before? I mean in the same dataset directory. I have modified the data.py a bit upon theirs. The file organization for the dataset is different from their code. Try to allocate a new directory for the preprocessed dataset. This may solve the problem.

**Comment by semchan** [comment]
Yes, I'm running the code from scratch.I have no run the CoMA code before, maybe it is caused by the data processing. would you please help me? the message as below:


  File "/usr/local/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 237, in propagate
    out = self.message(**msg_kwargs)
  File "/home/CV3D/Deep3DMM/layers.py", line 58, in message
    return norm.view(-1, 1, 1) * x_j
RuntimeError: The size of tensor a (29990) must match the size of tensor b (5023) at non-singleton dimension 0





Best Regards
 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zchen06/Deep3DMM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上7:25
***@***.***&gt;;
抄送:&nbsp;"Sem ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zchen06/Deep3DMM] When I run the training code after download COMA dataset, it pop out below error message, would you please help me? thanks  (#2)





 
Can you upload a screenshot of the output message? I cannot locate the position where the error happens.
 My guess is like this. Are you running the code from scratch? Did you run the CoMA code from Ranjan et al. 2018 before? I mean in the same dataset directory. I have modified the data.py a bit upon theirs. The file organization for the dataset is different from their code. Try to allocate a new directory for the preprocessed dataset. This may solves the problem.

**Comment by semchan** [comment]
I mean, I just download the dataset of COMA from [here](https://coma.is.tue.mpg.de/), the "Registered Data(3GB)" to "./datasets/COMA", and unzip the data into this folder. Then I run main.py, the error pop out. thanks.

**Comment by zchen06** [comment]
I think the problem is with the torch-geometric. Are you using the torch-geometric with the version specified in the 'requirements.txt'? A higher version torch-geometric may lead to such problem since the interface of torch-geometric has changed.

**Comment by Wanghaha2333** [comment]
@zchen06  Hi, after installing all your given version of packages, I still get the dimension error like above. Could you please help to check?
