### ISSUE TITLE
About layer in PYG2.0.2

### ISSUE THREAD

**Issue by MontaEllis** [zxchen110/Deep3DMM#3]
Hi, I notice that the code can only run on PYG-1.4.3, do you have any plans to update it to PYG-2.0.2?

**Comment by zchen06** [comment]
> Hi, I notice that the code can only run on PYG-1.4.3, do you have any plans to update it to PYG-2.0.2?

Hi @MontaEllis,  the PYG only influences the ChebConv_Coma() and Pool() classes in the layers.py. I have modified it to run with higher version PYG but am not certain whether it still works or not now. You can try the attached layers.py. Let me know whether it works or not. Thanks.
[layers.zip](https://github.com/zchen06/Deep3DMM/files/7432695/layers.zip)

**Comment by MontaEllis** [comment]
Thanks for you reply! Your code in layer.py still exists some tiny bugs. But with your nice help, I've succeed correcting the code.   I wonder if I can make a PR to flesh out your code.

**Comment by zchen06** [comment]
> Thanks for you reply! Your code in layer.py still exists some tiny bugs. But with your nice help, I've succeed correcting the code. I wonder if I can make a PR to flesh out your code.

sure, you are welcome to contribute to update the code.
